name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy container
        uses: azure/webapps-deploy@v2
        with:
          app-name: eduscore
          images: mycontainerregistry.azurecr.io/eduscore:latest
