# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eduscore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: eduscore.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7808AFF9AD01467C9880577DDB966012 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_4584833932664AA3B1DA6E49158F7265 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: eduscore.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7808AFF9AD01467C9880577DDB966012 }}/eduscore.azurecr.io/eduscore:latest:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F5CE1DC9C37845C4943F14AEC48316C3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_30C68A14194144F0B66013F25F7E428E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_28CADD85E39445B19692250DE17F69B6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'eduscore'
          slot-name: 'Production'
          images: 'eduscore.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7808AFF9AD01467C9880577DDB966012 }}/eduscore.azurecr.io/eduscore:latest:${{ github.sha }}'
          