# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eduscore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: eduscore.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_69B9DC414EF54FD195D1B5885ACEE498 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_4F062013BB7549AB8A9C990668F7E2C3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: eduscore.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_69B9DC414EF54FD195D1B5885ACEE498 }}/eduscore:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build

    steps:
<<<<<<< HEAD
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5A585AF9FA94B0498E2A0213A6E178C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EEA809AC146147798C42941A69B36500 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2676A75D9F2F42B5B8488B5A2F3816D8 }}
=======
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_247D51C46CE243E3AF5145941E0103E0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_013C454E61C14F88AC18DE8FF464A211 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6FA449A8F17741C696B823150CE52886 }}
>>>>>>> a6dd4d93268ce8298a1f1068ba56955fa9fb3ded

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
<<<<<<< HEAD
          app-name: "eduscore"
          slot-name: "Production"
          images: "eduscore.azurecr.io/eduscore:${{ github.sha }}"
=======
          app-name: 'eduscore'
          slot-name: 'Production'
          images: 'eduscore.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_69B9DC414EF54FD195D1B5885ACEE498 }}/eduscore:${{ github.sha }}'
          
>>>>>>> a6dd4d93268ce8298a1f1068ba56955fa9fb3ded
